[PHP]
extension_dir = "C:\Users\heric\AppData\Local\Microsoft\WinGet\Packages\PHP.PHP.8.3_Microsoft.Winget.Source_8wekyb3d8bbwe\ext"

extension=pdo_mysql
extension=mysqli

; Recommended for local dev
display_errors = On
error_reporting = E_ALL
